import type { Metadata } from "next";
import { APP_NAME, SOCIAL } from "@orbis/shared";
import { DocPage, docStyles as s } from "@/components/DocPage";

export const metadata: Metadata = { title: `Terms – ${APP_NAME}` };

export default function Terms() {
  return (
    <DocPage title="Terms of use" lede={<span className={s.updated}>Last updated October 3, 2026</span>}>
      <p>
        These terms cover your use of the {APP_NAME} website and studio (&quot;{APP_NAME}&quot;, &quot;we&quot;). By using it you agree to them. If you do not agree,
        please do not use {APP_NAME}.
      </p>

      <h2>A preview</h2>
      <p>
        {APP_NAME} is in preview. Features can change or stop working, and data can be reset. The service is provided as is, without warranties of any kind.
      </p>

      <h2>Credits</h2>
      <p>
        Credits in the preview are free, have no monetary value and cannot be exchanged or withdrawn. When paid credits launch, their rules will be added here
        before they go live.
      </p>

      <h2>Your agents and content</h2>
      <ul>
        <li>You are responsible for the instructions you write, the tasks you run and how you use the answers.</li>
        <li>Do not use {APP_NAME} for anything illegal, harmful, hateful, deceptive or that infringes other people&apos;s rights.</li>
        <li>Your instructions stay private. People who run your published agent see its character and skills, not your instructions.</li>
      </ul>

      <h2>AI answers</h2>
      <p>
        Answers are generated by AI and can be wrong, incomplete or out of date. Check anything important before you rely on it. Nothing on {APP_NAME} is
        financial, legal or investment advice.
      </p>

      <h2>Wallets and tokens</h2>
      <p>
        You are responsible for your wallet, its keys and the transactions you sign. Blockchain transactions cannot be reversed. A token has not launched yet; the
        only official contract address will be posted on this site and on our X account.
      </p>

      <h2>Changes and contact</h2>
      <p>
        We may update these terms. The date at the top shows the latest version. Questions:{" "}
        <a href={SOCIAL.x} target="_blank" rel="noopener noreferrer">
          message us on X
        </a>
        .
      </p>
    </DocPage>
  );
}
